### ISSUE TITLE
Language filter not filtering the language

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#663] opened 2018-02-27 12:56 UTC
When a user set his language to English, the Dashboard filter does not filter the courses and display all the courses the user are enrolled in. The same applies for Arabic

url: https://khda.proversity.org/

Steps
1.  Click on the link above and login.

Results
all the courses the user are enrolled are displayed, regarding the language preference of the user.

Expected Results
Only the courses should display according to the user language preference.

**Comment by mariushuman** [comment] 2018-02-27 12:57
cc @nicovanniekerk

**Comment by lidijarad** [comment] 2018-03-14 08:17
@mariushuman @nicovanniekerk, this was resolved. Problem initially caused by an update. Closing this issue.

**Closed as completed** 2018-03-14 08:17 UTC
Labels: bug
